# Generated by Django 5.0.6 on 2025-11-05 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Уровень сложности')),
                ('level', models.PositiveIntegerField(help_text='Число для сортировки (1-легкий, 2-средний, 3-сложный)', unique=True, verbose_name='Числовой уровень')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Программирование, Дизайн, Маркетинг', max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория темы',
                'verbose_name_plural': 'Категории тем',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZaekTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название темы (макс. 100 символов)', max_length=100, unique=True, verbose_name='Название темы')),
                ('comment', models.TextField(blank=True, help_text='Дополнительный комментарий', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZaekProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Уникальное название продукта', unique=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, help_text='Изображение продукта (необязательно)', null=True, upload_to='products/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, help_text='Ссылка на изображение продукта (если нет загруженного файла)', null=True, verbose_name='Ссылка на изображение')),
                ('comment', models.TextField(blank=True, help_text='Дополнительный комментарий', null=True, verbose_name='Комментарий')),
                ('category', models.ForeignKey(help_text='Категория', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='zaek.topiccategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZaekQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Текст вопроса', verbose_name='Вопрос')),
                ('comment', models.TextField(blank=True, help_text='Дополнительный комментарий', null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('difficulty', models.ForeignKey(help_text='Уровень сложности вопроса', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='zaek.difficultylevel', verbose_name='Уровень сложности')),
                ('product', models.ForeignKey(blank=True, help_text='Необязательная привязка к продукту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='zaek.zaekproduct', verbose_name='Связанный продукт')),
                ('topic', models.ForeignKey(help_text='Тема вопроса', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='zaek.zaektopic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZaekAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст ответа', max_length=500, verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='zaek.zaekquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-is_correct', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZaekUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.CharField(help_text='Уникальный идентификатор пользователя в Telegram', max_length=30, unique=True, verbose_name='ID в Telegram')),
                ('name_telegram', models.CharField(help_text='Имя пользователя в Telegram', max_length=200, verbose_name='Имя в Telegram')),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Общее количество данных пользователем ответов', verbose_name='Всего попыток')),
                ('correct_attempts', models.PositiveIntegerField(default=0, help_text='Количество верных ответов пользователя', verbose_name='Правильные ответы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Время последнего взаимодействия с ботом', verbose_name='Последняя активность')),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_telegram'], name='zaek_zaekus_id_tele_2eb9e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=260, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='zaek.zaekuser')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['-created_at'],
            },
        ),
    ]
