# Generated by Django 5.0.6 on 2025-11-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zaektopic',
            options={'ordering': ['name'], 'verbose_name': 'Тема вопроса', 'verbose_name_plural': 'Темы вопросов'},
        ),
        migrations.AddField(
            model_name='zaekquestion',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ссылка на изображение продукта', null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='zaektopic',
            name='comment',
            field=models.CharField(blank=True, help_text='Дополнительный комментарий', max_length=222, null=True, verbose_name='Комментарий'),
        ),
    ]
