# Generated by Django 5.0 on 2025-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0002_alter_zaekanswer_text_alter_zaekquestion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaekquestion',
            name='name',
            field=models.TextField(help_text='Текст вопроса', verbose_name='Вопрос'),
        ),
    ]
