# Generated by Django 5.0.6 on 2026-06-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0002_alter_zaektopic_options_zaekquestion_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultylevel',
            name='level',
            field=models.PositiveIntegerField(help_text='Чем выше число (1-простой, 2-средний, 3-сложный)', unique=True, verbose_name='Номер уровня'),
        ),
        migrations.AlterField(
            model_name='difficultylevel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Название уровня'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='name',
            field=models.CharField(help_text='Например: электрика, оптика, механика', max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='zaekanswer',
            name='text',
            field=models.TextField(help_text='Текст ответа', max_length=500, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='zaekproduct',
            name='category',
            field=models.ForeignKey(help_text='Категория продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='zaek.topiccategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='zaekproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение продукта (желательно)', null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='zaekproduct',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ссылка на внешнее изображение (если нет загруженного файла)', null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='zaekquestion',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ссылка на изображение для вопроса', null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='zaekquestion',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Привязка продукта к вопросу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='zaek.zaekproduct', verbose_name='Продукт вопроса'),
        ),
        migrations.AlterField(
            model_name='zaektopic',
            name='name',
            field=models.CharField(help_text='Уникальное название темы (макс. 100 символов)', max_length=100, unique=True, verbose_name='Имя темы'),
        ),
        migrations.AlterField(
            model_name='zaekuser',
            name='correct_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Количество правильных ответов пользователя', verbose_name='Правильных ответов'),
        ),
        migrations.AlterField(
            model_name='zaekuser',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество попыток ответить на вопросы', verbose_name='Всего попыток'),
        ),
    ]
