# Generated by Django 5.0 on 2025-07-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0003_alter_zaekquestion_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaekProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(help_text='Уникальной артикул (макс. 100 символов)', max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.TextField(help_text='Уникальное название', unique=True, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='zaekquestion',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Необязательная привязка к продукту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='zaek.zaekproduct', verbose_name='Связанный продукт'),
        ),
    ]
