# Generated by Django 5.0 on 2025-07-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0004_zaekproduct_zaekquestion_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zaekproduct',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='zaekquestion',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий', null=True, verbose_name='Вопрос'),
        ),
    ]
