# Generated by Django 5.0 on 2025-07-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0005_alter_zaekproduct_options_zaekquestion_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaekquestion',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий', null=True, verbose_name='Комментарий'),
        ),
        migrations.CreateModel(
            name='ZaekUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.CharField(help_text='Уникальный идентификатор пользователя в Telegram', max_length=15, unique=True, verbose_name='ID в Telegram')),
                ('name_telegram', models.CharField(help_text='Уникальный идентификатор пользователя в Telegram', max_length=15, unique=True, verbose_name='Имя в телегам в Telegram')),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Общее количество данных пользователем ответов', verbose_name='Всего попыток')),
                ('correct_attempts', models.PositiveIntegerField(default=0, help_text='Количество верных ответов пользователя', verbose_name='Правильные ответы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Время последнего взаимодействия с ботом', verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_telegram'], name='zaek_zaekus_id_tele_2eb9e6_idx')],
            },
        ),
    ]
