# Generated by Django 5.0 on 2025-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0006_alter_zaekquestion_comment_zaekuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaekuser',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
