# Generated by Django 5.0 on 2025-07-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0007_zaekuser_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaekuser',
            name='id_telegram',
            field=models.CharField(help_text='Уникальный идентификатор пользователя в Telegram', max_length=30, unique=True, verbose_name='ID в Telegram'),
        ),
        migrations.AlterField(
            model_name='zaekuser',
            name='name_telegram',
            field=models.CharField(help_text='Уникальный идентификатор пользователя в Telegram', max_length=200, unique=True, verbose_name='Имя в телегам в Telegram'),
        ),
    ]
