# Generated by Django 5.0 on 2025-08-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0008_alter_zaekuser_id_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaekanswer',
            name='text',
            field=models.TextField(help_text='Подробный текст ответа', verbose_name='Ответ'),
        ),
    ]
