# Generated by Django 5.0 on 2025-08-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0009_alter_zaekanswer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaekanswer',
            name='text',
            field=models.TextField(help_text='Подробный текст ответа', max_length=64, verbose_name='Ответ'),
        ),
    ]
