# Generated by Django 5.0 on 2025-08-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0011_alter_zaekanswer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaekproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение продукта (необязательно)', null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
