# Generated by Django 5.0 on 2025-08-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0012_zaekproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaekproduct',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Тема, к которой относится продукт', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='zaek.zaektopic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='zaekanswer',
            name='text',
            field=models.TextField(help_text='Текст ответа', max_length=119, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='zaekproduct',
            name='art',
            field=models.CharField(help_text='Уникальный артикул (макс. 100 символов)', max_length=100, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='zaekproduct',
            name='name',
            field=models.TextField(help_text='Уникальное название продукта', unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='zaekquestion',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительный комментарий', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='zaekquestion',
            name='topic',
            field=models.ForeignKey(help_text='Тема вопроса', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='zaek.zaektopic', verbose_name='Тема'),
        ),
    ]
