# Generated by Django 5.0 on 2025-08-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0013_zaekproduct_topic_alter_zaekanswer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaekquestion',
            name='topic',
            field=models.ForeignKey(help_text='Тема вопроса', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='zaek.zaektopic', verbose_name='Тема'),
        ),
    ]
