# Generated by Django 5.0 on 2025-08-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0014_alter_zaekquestion_topic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zaekquestion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='zaekanswer',
            name='text',
            field=models.TextField(help_text='Текст ответа', max_length=500, verbose_name='Ответ'),
        ),
    ]
