# Generated by Django 5.0 on 2025-08-21 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0015_alter_zaekquestion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaekproduct',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ссылка на изображение продукта (если нет загруженного файла)', null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='zaekquestion',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Тема вопроса', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='zaek.zaektopic', verbose_name='Тема'),
        ),
    ]
