# Generated by Django 5.0 on 2025-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0016_zaekproduct_image_url_alter_zaekquestion_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaektopic',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительный комментарий', null=True, verbose_name='Комментарий'),
        ),
    ]
